# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

images:
  tags:
    odl_controller: docker.io/sapan2211/odl-karaf-boron:5
  pull_policy: "IfNotPresent"

network:
  node_port:
    dashboard: 35182
  port:
    ovsdb_manager: 6640
    openflow: 6653
    odl_neutron_rest: 8080
    dashboard: 8181

labels:
  controller:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled

pod:
  user:
    odl:
      uid: 0
  affinity:
      anti:
        type:
          default: preferredDuringSchedulingIgnoredDuringExecution
        topologyKey:
          default: kubernetes.io/hostname
  replicas:
    controller: 1
  mounts:
    odl_controller:
      odl_controller:
      init_container: null
  lifecycle:
    upgrades:
      deployments:
        revision_history: 3
        pod_replacement_strategy: RollingUpdate
        rolling_update:
          max_unavailable: 1
          max_surge: 3
        odl:
          enabled: false
          min_ready_seconds: 0
          max_unavailable: 1
  resources:
    enabled: true
    controller:
      requests:
        memory: "2048Mi"
        cpu: "1000m"
      limits:
        memory: "4096Mi"
        cpu: "2000m"

manifests:
  configmap_bin: true
  configmap_etc: false
  deployment: true
  service:
    ovs: true
    dashboard: true

endpoints:
  odl:
    name: odl
    hosts:
      default: odl-controller
      public: odl
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: http
  dashboard:
    name: odl-dashboard
    hosts:
      default: odl-dashboard
      public: odl-ui
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: http
